export default {
	GET_AUTH: 'GET_AUTH',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	GET_MESSAGES: 'GET_MESSAGES',
	GET_CHAT_INFO: 'GET_CHAT_INFO',
	GET_CHAT_PARTICIPANTS: 'GET_CHAT_PARTICIPANTS',
	DELETE_FROM_CHAT: 'DELETE_FROM_CHAT'
}
